// resources/js/pages/job-seeker/Portfolio.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { portfolio } from '@/routes';
import portfolioRoutes from '@/routes/portfolio';
import { type BreadcrumbItem } from '@/types';
import { Head, Form, router } from '@inertiajs/vue3';
import { Plus, ExternalLink, Edit, Trash2, Github, Calendar } from 'lucide-vue-next';
import { ref } from 'vue';

const props = defineProps<{
    projects?: Array<{
        id: number;
        title: string;
        description?: string;
        url?: string;
        repository_url?: string;
        technologies?: string[];
        start_date?: string;
        end_date?: string;
        image?: string;
        is_featured: boolean;
    }>;
}>();

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Portfolio',
        href: portfolio().url,
    },
];

const isDialogOpen = ref(false);
const editingProject = ref<any>(null);

const form = ref({
    title: '',
    description: '',
    url: '',
    repository_url: '',
    technologies: [] as string[],
    start_date: '',
    end_date: '',
    image: '',
    is_featured: false,
});

const techInput = ref('');

const openDialog = (project?: any) => {
    editingProject.value = project || null;
    if (project) {
        form.value = {
            title: project.title || '',
            description: project.description || '',
            url: project.url || '',
            repository_url: project.repository_url || '',
            technologies: project.technologies || [],
            start_date: project.start_date || '',
            end_date: project.end_date || '',
            image: project.image || '',
            is_featured: project.is_featured || false,
        };
    } else {
        form.value = {
            title: '',
            description: '',
            url: '',
            repository_url: '',
            technologies: [],
            start_date: '',
            end_date: '',
            image: '',
            is_featured: false,
        };
    }
    isDialogOpen.value = true;
};

const addTechnology = () => {
    if (techInput.value.trim() && !form.value.technologies.includes(techInput.value.trim())) {
        form.value.technologies.push(techInput.value.trim());
        techInput.value = '';
    }
};

const removeTechnology = (tech: string) => {
    form.value.technologies = form.value.technologies.filter(t => t !== tech);
};

const submitForm = () => {
    if (editingProject.value) {
        router.put(portfolioRoutes.update(editingProject.value.id).url, form.value, {
            onSuccess: () => {
                isDialogOpen.value = false;
                editingProject.value = null;
            },
        });
    } else {
        router.post(portfolioRoutes.store().url, form.value, {
            onSuccess: () => {
                isDialogOpen.value = false;
                editingProject.value = null;
            },
        });
    }
};

const deleteProject = (id: number) => {
    if (confirm('Are you sure you want to delete this project?')) {
        router.delete(portfolioRoutes.destroy(id).url, {
            onSuccess: () => {
                // Project deleted
            },
        });
    }
};
</script>

<template>
    <Head title="Portfolio" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="flex h-full flex-1 flex-col gap-6 p-6">
            <div class="flex items-center justify-between">
                <div>
                    <h1 class="text-3xl font-bold tracking-tight">Project Portfolio</h1>
                    <p class="text-muted-foreground mt-2">
                        Showcase your projects and build a compelling portfolio
                    </p>
                </div>
                <Dialog :open="isDialogOpen" @update:open="(val) => { isDialogOpen = val; if (!val) editingProject = null; }">
                    <DialogTrigger as-child>
                        <Button @click="openDialog()">
                            <Plus class="mr-2 h-4 w-4" />
                            Add Project
                        </Button>
                    </DialogTrigger>
                    <DialogContent class="max-w-2xl max-h-[90vh] overflow-y-auto">
                        <DialogHeader>
                            <DialogTitle>{{ editingProject ? 'Edit Project' : 'Add New Project' }}</DialogTitle>
                            <DialogDescription>Add details about your project to showcase your skills</DialogDescription>
                        </DialogHeader>
                        <div class="space-y-6">
                            <div class="grid gap-2">
                                <Label for="title">Title</Label>
                                <Input id="title" v-model="form.title" placeholder="Project title" required />
                            </div>
                            <div class="grid gap-2">
                                <Label for="description">Description</Label>
                                <textarea
                                    id="description"
                                    v-model="form.description"
                                    class="w-full min-h-[100px] rounded-md border border-input bg-background px-3 py-2 text-sm"
                                    placeholder="Project description"
                                />
                            </div>
                            <div class="grid grid-cols-2 gap-4">
                                <div class="grid gap-2">
                                    <Label for="url">Project URL</Label>
                                    <Input id="url" v-model="form.url" type="url" placeholder="https://..." />
                                </div>
                                <div class="grid gap-2">
                                    <Label for="repository_url">Repository URL</Label>
                                    <Input id="repository_url" v-model="form.repository_url" type="url" placeholder="https://github.com/..." />
                                </div>
                            </div>
                            <div class="grid grid-cols-2 gap-4">
                                <div class="grid gap-2">
                                    <Label for="start_date">Start Date</Label>
                                    <Input id="start_date" v-model="form.start_date" type="date" />
                                </div>
                                <div class="grid gap-2">
                                    <Label for="end_date">End Date</Label>
                                    <Input id="end_date" v-model="form.end_date" type="date" />
                                </div>
                            </div>
                            <div class="grid gap-2">
                                <Label>Technologies</Label>
                                <div class="flex gap-2">
                                    <Input v-model="techInput" placeholder="Add technology" @keyup.enter="addTechnology" />
                                    <Button type="button" @click="addTechnology">Add</Button>
                                </div>
                                <div v-if="form.technologies.length > 0" class="flex flex-wrap gap-2 mt-2">
                                    <span
                                        v-for="tech in form.technologies"
                                        :key="tech"
                                        class="inline-flex items-center gap-1 px-2 py-1 bg-primary/10 text-primary rounded-md text-sm"
                                    >
                                        {{ tech }}
                                        <button type="button" @click="removeTechnology(tech)" class="hover:text-destructive">×</button>
                                    </span>
                                </div>
                            </div>
                            <div class="flex items-center gap-2">
                                <input id="is_featured" v-model="form.is_featured" type="checkbox" class="rounded" />
                                <Label for="is_featured">Feature this project</Label>
                            </div>
                        </div>
                        <DialogFooter>
                            <Button variant="outline" @click="isDialogOpen = false">Cancel</Button>
                            <Button @click="submitForm">{{ editingProject ? 'Update' : 'Create' }}</Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            </div>

            <div v-if="projects && projects.length > 0" class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                <Card v-for="project in projects" :key="project.id" class="shadow-sm hover:shadow-md transition-shadow">
                    <CardHeader>
                        <div class="flex items-start justify-between">
                            <CardTitle class="text-lg">{{ project.title }}</CardTitle>
                            <div class="flex gap-2">
                                <Button variant="ghost" size="sm" @click="openDialog(project)">
                                    <Edit class="h-4 w-4" />
                                </Button>
                                <Button variant="ghost" size="sm" @click="deleteProject(project.id)">
                                    <Trash2 class="h-4 w-4 text-destructive" />
                                </Button>
                            </div>
                        </div>
                        <CardDescription v-if="project.description">{{ project.description }}</CardDescription>
                    </CardHeader>
                    <CardContent class="space-y-3">
                        <div v-if="project.technologies && project.technologies.length > 0" class="flex flex-wrap gap-1">
                            <span
                                v-for="tech in project.technologies"
                                :key="tech"
                                class="px-2 py-1 bg-secondary text-secondary-foreground rounded text-xs"
                            >
                                {{ tech }}
                            </span>
                        </div>
                        <div v-if="project.start_date || project.end_date" class="flex items-center gap-2 text-sm text-muted-foreground">
                            <Calendar class="h-4 w-4" />
                            <span>{{ project.start_date }} - {{ project.end_date || 'Present' }}</span>
                        </div>
                        <div class="flex gap-2">
                            <Button v-if="project.url" variant="outline" size="sm" as-child>
                                <a :href="project.url" target="_blank" rel="noopener noreferrer">
                                    <ExternalLink class="mr-2 h-4 w-4" />
                                    View
                                </a>
                            </Button>
                            <Button v-if="project.repository_url" variant="outline" size="sm" as-child>
                                <a :href="project.repository_url" target="_blank" rel="noopener noreferrer">
                                    <Github class="mr-2 h-4 w-4" />
                                    Code
                                </a>
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            </div>
            <div v-else class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                <Card class="shadow-sm">
                    <CardHeader>
                        <CardTitle>No projects yet</CardTitle>
                        <CardDescription>
                            Start building your portfolio by adding your first project
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <Button variant="outline" class="w-full" @click="openDialog()">
                            <Plus class="mr-2 h-4 w-4" />
                            Create First Project
                        </Button>
                    </CardContent>
                </Card>
            </div>
        </div>
    </AppLayout>
</template>

// resources/js/pages/portfolio/index.tsx
import { useState } from 'react';
import { Head, Link } from '@inertiajs/react';
import AppLayout from '@/layouts/app-layout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
    FolderOpen,
    ExternalLink,
    Github,
    Star,
    GitFork,
    Calendar,
    Code,
    Eye,
    Plus,
    Edit,
    Trash2,
    Award,
    MessageSquare,
    Users,
    TrendingUp,
    Globe,
} from 'lucide-react';

interface Project {
    id: number;
    title: string;
    description: string;
    technologies: string[];
    image: string;
    live_url: string;
    github_url: string;
    featured: boolean;
    created_date: string;
    category: string;
    status: string;
}

interface Repository {
    id: number;
    name: string;
    description: string;
    language: string;
    stars: number;
    forks: number;
    updated: string;
    url: string;
}

interface Achievement {
    id: number;
    title: string;
    description: string;
    icon: string;
    earned_date: string;
}

interface Testimonial {
    id: number;
    name: string;
    role: string;
    company: string;
    content: string;
    rating: number;
}

interface Props {
    projects: Project[];
    repositories: Repository[];
    achievements: Achievement[];
    testimonials: Testimonial[];
}

export default function PortfolioIndex({ projects, repositories, achievements, testimonials }: Props) {
    const [activeTab, setActiveTab] = useState('projects');

    const getStatusColor = (status: string) => {
        switch (status.toLowerCase()) {
            case 'completed': return 'bg-green-100 text-green-800';
            case 'in progress': return 'bg-blue-100 text-blue-800';
            case 'planned': return 'bg-yellow-100 text-yellow-800';
            default: return 'bg-gray-100 text-gray-800';
        }
    };

    const getCategoryColor = (category: string) => {
        switch (category.toLowerCase()) {
            case 'web application': return 'bg-blue-100 text-blue-800';
            case 'dashboard': return 'bg-purple-100 text-purple-800';
            case 'mobile app': return 'bg-green-100 text-green-800';
            case 'api': return 'bg-orange-100 text-orange-800';
            default: return 'bg-gray-100 text-gray-800';
        }
    };

    const renderStars = (rating: number) => {
        return Array.from({ length: 5 }, (_, i) => (
            <Star
                key={i}
                className={`h-4 w-4 ${
                    i < rating ? 'fill-yellow-400 text-yellow-400' : 'text-gray-300'
                }`}
            />
        ));
    };

    return (
        <AppLayout>
            <Head title="Portfolio & Projects" />
            <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Portfolio & Projects</h1>
                        <p className="text-gray-600 dark:text-gray-400 mt-1">
                            Showcase your work and track your development journey
                        </p>
                    </div>
                    <div className="flex items-center gap-4">
                        <div className="text-right">
                            <div className="text-2xl font-bold text-gray-900 dark:text-white">{projects.length}</div>
                            <div className="text-sm text-gray-600 dark:text-gray-400">Projects</div>
                        </div>
                        <div className="text-right">
                            <div className="text-2xl font-bold text-gray-900 dark:text-white">{repositories.length}</div>
                            <div className="text-sm text-gray-600 dark:text-gray-400">Repositories</div>
                        </div>
                        <Button className="bg-purple-600 hover:bg-purple-700">
                            <Plus className="h-4 w-4 mr-2" />
                            Add Project
                        </Button>
                    </div>
                </div>

                {/* Quick Stats */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                    <Card>
                        <CardContent className="p-6">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Total Stars</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white">
                                        {repositories.reduce((sum, repo) => sum + repo.stars, 0)}
                                    </p>
                                </div>
                                <div className="w-12 h-12 bg-yellow-100 dark:bg-yellow-900 rounded-full flex items-center justify-center">
                                    <Star className="h-6 w-6 text-yellow-600 dark:text-yellow-400" />
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent className="p-6">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Total Forks</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white">
                                        {repositories.reduce((sum, repo) => sum + repo.forks, 0)}
                                    </p>
                                </div>
                                <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900 rounded-full flex items-center justify-center">
                                    <GitFork className="h-6 w-6 text-blue-600 dark:text-blue-400" />
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent className="p-6">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Achievements</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white">{achievements.length}</p>
                                </div>
                                <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900 rounded-full flex items-center justify-center">
                                    <Award className="h-6 w-6 text-purple-600 dark:text-purple-400" />
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent className="p-6">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm font-medium text-gray-600 dark:text-gray-400">Testimonials</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white">{testimonials.length}</p>
                                </div>
                                <div className="w-12 h-12 bg-green-100 dark:bg-green-900 rounded-full flex items-center justify-center">
                                    <MessageSquare className="h-6 w-6 text-green-600 dark:text-green-400" />
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Tabs */}
                <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                    <TabsList className="grid w-full grid-cols-4">
                        <TabsTrigger value="projects" className="flex items-center gap-2">
                            <FolderOpen className="h-4 w-4" />
                            Projects
                        </TabsTrigger>
                        <TabsTrigger value="repositories" className="flex items-center gap-2">
                            <Github className="h-4 w-4" />
                            Repositories
                        </TabsTrigger>
                        <TabsTrigger value="achievements" className="flex items-center gap-2">
                            <Award className="h-4 w-4" />
                            Achievements
                        </TabsTrigger>
                        <TabsTrigger value="testimonials" className="flex items-center gap-2">
                            <MessageSquare className="h-4 w-4" />
                            Testimonials
                        </TabsTrigger>
                    </TabsList>

                    {/* Projects */}
                    <TabsContent value="projects" className="space-y-6">
                        <div className="grid gap-6">
                            {projects.map((project) => (
                                <Card key={project.id} className="hover:shadow-lg transition-shadow">
                                    <CardHeader>
                                        <div className="flex items-start justify-between">
                                            <div className="flex-1">
                                                <div className="flex items-center gap-3 mb-2">
                                                    <CardTitle className="text-xl">{project.title}</CardTitle>
                                                    {project.featured && (
                                                        <Badge className="bg-purple-100 text-purple-800">
                                                            Featured
                                                        </Badge>
                                                    )}
                                                </div>
                                                <CardDescription className="text-base">
                                                    {project.description}
                                                </CardDescription>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <Button variant="outline" size="sm">
                                                    <Edit className="h-4 w-4 mr-2" />
                                                    Edit
                                                </Button>
                                                <Button asChild>
                                                    <Link href={`/portfolio/${project.id}`}>
                                                        <Eye className="h-4 w-4 mr-2" />
                                                        View
                                                    </Link>
                                                </Button>
                                            </div>
                                        </div>
                                    </CardHeader>
                                    <CardContent>
                                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
                                            <div className="flex items-center gap-2 text-gray-600 dark:text-gray-400">
                                                <Calendar className="h-4 w-4" />
                                                <span>{new Date(project.created_date).toLocaleDateString()}</span>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <Badge className={getCategoryColor(project.category)}>
                                                    {project.category}
                                                </Badge>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <Badge className={getStatusColor(project.status)}>
                                                    {project.status}
                                                </Badge>
                                            </div>
                                            <div className="flex items-center gap-2 text-gray-600 dark:text-gray-400">
                                                <Code className="h-4 w-4" />
                                                <span>{project.technologies.length} technologies</span>
                                            </div>
                                        </div>

                                        <div className="flex flex-wrap gap-2 mb-4">
                                            {project.technologies.map((tech, index) => (
                                                <Badge key={index} variant="outline">
                                                    {tech}
                                                </Badge>
                                            ))}
                                        </div>

                                        <div className="flex items-center gap-4">
                                            <Button variant="outline" size="sm" asChild>
                                                <a href={project.live_url} target="_blank" rel="noopener noreferrer">
                                                    <Globe className="h-4 w-4 mr-2" />
                                                    Live Demo
                                                    <ExternalLink className="h-4 w-4 ml-2" />
                                                </a>
                                            </Button>
                                            <Button variant="outline" size="sm" asChild>
                                                <a href={project.github_url} target="_blank" rel="noopener noreferrer">
                                                    <Github className="h-4 w-4 mr-2" />
                                                    Source Code
                                                    <ExternalLink className="h-4 w-4 ml-2" />
                                                </a>
                                            </Button>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </TabsContent>

                    {/* Repositories */}
                    <TabsContent value="repositories" className="space-y-6">
                        <div className="grid gap-4">
                            {repositories.map((repo) => (
                                <Card key={repo.id}>
                                    <CardContent className="p-6">
                                        <div className="flex items-center justify-between">
                                            <div className="flex-1">
                                                <div className="flex items-center gap-3 mb-2">
                                                    <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                                                        {repo.name}
                                                    </h3>
                                                    <Badge variant="outline">
                                                        {repo.language}
                                                    </Badge>
                                                </div>
                                                <p className="text-gray-600 dark:text-gray-400 mb-3">
                                                    {repo.description}
                                                </p>
                                                <div className="flex items-center gap-4 text-sm text-gray-500">
                                                    <div className="flex items-center gap-1">
                                                        <Star className="h-4 w-4" />
                                                        <span>{repo.stars}</span>
                                                    </div>
                                                    <div className="flex items-center gap-1">
                                                        <GitFork className="h-4 w-4" />
                                                        <span>{repo.forks}</span>
                                                    </div>
                                                    <div className="flex items-center gap-1">
                                                        <Calendar className="h-4 w-4" />
                                                        <span>Updated {new Date(repo.updated).toLocaleDateString()}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <Button variant="outline" size="sm" asChild>
                                                <a href={repo.url} target="_blank" rel="noopener noreferrer">
                                                    <Github className="h-4 w-4 mr-2" />
                                                    View
                                                    <ExternalLink className="h-4 w-4 ml-2" />
                                                </a>
                                            </Button>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </TabsContent>

                    {/* Achievements */}
                    <TabsContent value="achievements" className="space-y-6">
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {achievements.map((achievement) => (
                                <Card key={achievement.id} className="text-center">
                                    <CardContent className="p-6">
                                        <div className="text-4xl mb-3">{achievement.icon}</div>
                                        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                                            {achievement.title}
                                        </h3>
                                        <p className="text-gray-600 dark:text-gray-400 mb-3">
                                            {achievement.description}
                                        </p>
                                        <div className="flex items-center justify-center gap-2 text-sm text-gray-500">
                                            <Calendar className="h-4 w-4" />
                                            <span>Earned {new Date(achievement.earned_date).toLocaleDateString()}</span>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </TabsContent>

                    {/* Testimonials */}
                    <TabsContent value="testimonials" className="space-y-6">
                        <div className="grid gap-6">
                            {testimonials.map((testimonial) => (
                                <Card key={testimonial.id}>
                                    <CardContent className="p-6">
                                        <div className="flex items-start gap-4">
                                            <div className="w-12 h-12 bg-gray-100 dark:bg-gray-800 rounded-full flex items-center justify-center">
                                                <Users className="h-6 w-6 text-gray-600 dark:text-gray-400" />
                                            </div>
                                            <div className="flex-1">
                                                <div className="flex items-center gap-2 mb-2">
                                                    <h3 className="font-semibold text-gray-900 dark:text-white">
                                                        {testimonial.name}
                                                    </h3>
                                                    <div className="flex items-center gap-1">
                                                        {renderStars(testimonial.rating)}
                                                    </div>
                                                </div>
                                                <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                                                    {testimonial.role} at {testimonial.company}
                                                </p>
                                                <p className="text-gray-700 dark:text-gray-300 italic">
                                                    "{testimonial.content}"
                                                </p>
                                            </div>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </TabsContent>
                </Tabs>
            </div>
        </AppLayout>
    );
}
