// resources/js/components/app-sidebar.tsx
import { NavFooter } from '@/components/nav-footer';
import { NavMain } from '@/components/nav-main';
import { NavUser } from '@/components/nav-user';
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem } from '@/components/ui/sidebar';
import { dashboard } from '@/routes';
import { type NavItem } from '@/types';
import { Link } from '@inertiajs/react';
import {
    BookOpen,
    Folder,
    LayoutGrid,
    Upload,
    Target,
    Brain,
    Lightbulb,
    FileText,
    History,
    TrendingUp,
    MessageCircle,
    Briefcase,
    GraduationCap,
    Users,
    BarChart3,
    FolderOpen
} from 'lucide-react';
import AppLogo from './app-logo';

const mainNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: dashboard(),
        icon: LayoutGrid,
    },
    {
        title: 'Resume Management',
        href: '/resume',
        icon: Upload,
    },
    {
        title: 'My Skill Profile',
        href: '/skills',
        icon: Target,
    },
    {
        title: 'Job Matching',
        href: '/job-matching',
        icon: Briefcase,
    },
    {
        title: 'Learning & Development',
        href: '/learning',
        icon: GraduationCap,
    },
    {
        title: 'Interview Prep',
        href: '/interview',
        icon: Users,
    },
    {
        title: 'Career Analytics',
        href: '/career-analytics',
        icon: BarChart3,
    },
    {
        title: 'Portfolio & Projects',
        href: '/portfolio',
        icon: FolderOpen,
    },
    {
        title: 'Quizzes',
        href: '/quizzes',
        icon: Brain,
    },
    {
        title: 'Suggestions',
        href: '/recommendations',
        icon: Lightbulb,
    },
    {
        title: 'Ask AI',
        href: '/ai-chat',
        icon: MessageCircle,
    },
];

const footerNavItems: NavItem[] = [
    {
        title: 'GitHub Repository',
        href: 'https://github.com/your-username/skilldrift',
        icon: Folder,
    },
    {
        title: 'Documentation',
        href: 'https://skilldrift.com/docs',
        icon: BookOpen,
    },
];

export function AppSidebar() {
    return (
        <Sidebar collapsible="icon" variant="inset">
            <SidebarHeader>
                <SidebarMenu>
                    <SidebarMenuItem>
                        <SidebarMenuButton size="lg" asChild>
                            <Link href={dashboard()} prefetch>
                                <AppLogo />
                            </Link>
                        </SidebarMenuButton>
                    </SidebarMenuItem>
                </SidebarMenu>
            </SidebarHeader>

            <SidebarContent>
                <NavMain items={mainNavItems} />
            </SidebarContent>

            <SidebarFooter>
                <NavFooter items={footerNavItems} className="mt-auto" />
                <NavUser />
            </SidebarFooter>
        </Sidebar>
    );
}

// resources/js/components/AppSidebar.vue
<script setup lang="ts">
import NavMain from '@/components/NavMain.vue';
import NavUser from '@/components/NavUser.vue';
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from '@/components/ui/sidebar';
import { dashboard } from '@/routes';
import { edit as profileEdit } from '@/routes/profile';
import { cvReview } from '@/routes';
import { atsScoring } from '@/routes';
import { mockInterview } from '@/routes';
import { portfolio, profileScore, skillExpectations, jobApplications } from '@/routes';
import { postJobs, reviewCandidates, filterCandidates, subscriptions } from '@/routes';
import { userManagement, analytics, payments, companyManagement, hrManagement } from '@/routes';
import { type NavItem, type UserRole } from '@/types';
import { Link, usePage } from '@inertiajs/vue3';
import {
    LayoutGrid,
    FileText,
    FileCheck,
    Video,
    Settings,
    Briefcase,
    TrendingUp,
    Target,
    FileSearch,
    FolderKanban,
    Users,
    BarChart3,
    CreditCard,
    Building2,
    UserCog,
    ClipboardList,
} from 'lucide-vue-next';
import { computed } from 'vue';
import AppLogo from './AppLogo.vue';

const page = usePage();
const userRole = computed(() => (page.props.auth?.user?.role || 'job_seeker') as UserRole);

// Job Seeker Navigation Items
const jobSeekerNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: dashboard(),
        icon: LayoutGrid,
    },
    {
        title: 'CV Review',
        href: cvReview(),
        icon: FileText,
    },
    {
        title: 'ATS Scoring',
        href: atsScoring(),
        icon: FileCheck,
    },
    {
        title: 'Mock Interview',
        href: mockInterview(),
        icon: Video,
    },
    {
        title: 'Portfolio',
        href: portfolio(),
        icon: FolderKanban,
    },
    {
        title: 'Profile Score',
        href: profileScore(),
        icon: TrendingUp,
    },
    {
        title: 'Skill Expectations',
        href: skillExpectations(),
        icon: Target,
    },
    {
        title: 'Job Applications',
        href: jobApplications(),
        icon: FileSearch,
    },
    {
        title: 'Settings',
        href: profileEdit(),
        icon: Settings,
    },
];

// HR Professional Navigation Items
const hrProfessionalNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: dashboard(),
        icon: LayoutGrid,
    },
    {
        title: 'Post Jobs',
        href: postJobs(),
        icon: Briefcase,
    },
    {
        title: 'Review Candidates',
        href: reviewCandidates(),
        icon: Users,
    },
    {
        title: 'Filter Candidates',
        href: filterCandidates(),
        icon: FileSearch,
    },
    {
        title: 'Applied Candidates',
        href: reviewCandidates(),
        icon: ClipboardList,
    },
    {
        title: 'Subscriptions',
        href: subscriptions(),
        icon: CreditCard,
    },
    {
        title: 'Settings',
        href: profileEdit(),
        icon: Settings,
    },
];

// Admin Navigation Items
const adminNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: dashboard(),
        icon: LayoutGrid,
    },
    {
        title: 'User Management',
        href: userManagement(),
        icon: Users,
    },
    {
        title: 'Job Seekers',
        href: userManagement(),
        icon: UserCog,
    },
    {
        title: 'Companies',
        href: companyManagement(),
        icon: Building2,
    },
    {
        title: 'HR Professionals',
        href: hrManagement(),
        icon: Users,
    },
    {
        title: 'Analytics',
        href: analytics(),
        icon: BarChart3,
    },
    {
        title: 'Payments',
        href: payments(),
        icon: CreditCard,
    },
    {
        title: 'Settings',
        href: profileEdit(),
        icon: Settings,
    },
];

const mainNavItems = computed(() => {
    switch (userRole.value) {
        case 'hr_professional':
            return hrProfessionalNavItems;
        case 'admin':
            return adminNavItems;
        case 'job_seeker':
        default:
            return jobSeekerNavItems;
    }
});
</script>

<template>
    <Sidebar collapsible="icon" variant="inset">
        <SidebarHeader>
            <SidebarMenu>
                <SidebarMenuItem>
                    <SidebarMenuButton size="lg" as-child>
                        <Link :href="dashboard()">
                            <AppLogo />
                        </Link>
                    </SidebarMenuButton>
                </SidebarMenuItem>
            </SidebarMenu>
        </SidebarHeader>

        <SidebarContent>
            <NavMain :items="mainNavItems" />
        </SidebarContent>

        <SidebarFooter>
            <NavUser />
        </SidebarFooter>
    </Sidebar>
    <slot />
</template>
